name: New Issue Submitted

on: 
  issues:
    types: [opened]

jobs:
  print-issue:
    runs-on: ubuntu-latest
    steps:
      - name: "Display Message"
        run: |
          echo "An issue has been submitted!"
          echo "The issue was titled: ${{ github.event.issue.title }}"
          echo "It was posted by: ${{ github.event.issue.actor }}"

